In [16]:
df_titanic = pd.get_dummies(df1, columns=['Pclass', 'Embarked', 'Sex'], drop_first=True)

In [17]:
df_titanic.head()

,Survived,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,0,22.0,7.2500,0,False,True,False,True,True
1,1,38.0,71.2833,0,False,False,False,False,False
2,1,26.0,7.9250,1,False,True,False,True,False
3,1,35.0,53.1000,0,False,False,False,True,False
4,0,35.0,8.0500,1,False,True,False,True,True

In [20]:
x = df_titanic.drop(['Survived'], axis = 1)
y = df_titanic['Survived']

In [21]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [22]:
trans_mm = MinMaxScaler()
trans_ss = StandardScaler()

In [23]:
df_mm = trans_mm.fit_transform(x)
pd.DataFrame(df_mm)

            0         1    2    3    4    5    6    7
0    0.271174  0.014151  0.0  0.0  1.0  0.0  1.0  1.0
1    0.472229  0.139136  0.0  0.0  0.0  0.0  0.0  0.0
2    0.321438  0.015469  1.0  0.0  1.0  0.0  1.0  0.0
3    0.434531  0.103644  0.0  0.0  0.0  0.0  1.0  0.0
4    0.434531  0.015713  1.0  0.0  1.0  0.0  1.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...
886  0.334004  0.025374  1.0  1.0  0.0  0.0  1.0  1.0
887  0.233476  0.058556  1.0  0.0  0.0  0.0  1.0  0.0
888       NaN  0.045771  0.0  0.0  1.0  0.0  1.0  0.0
889  0.321438  0.058556  1.0  0.0  0.0  0.0  0.0  1.0
890  0.396833  0.015127  1.0  0.0  1.0  1.0  0.0  1.0

[891 rows x 8 columns]

In [24]:
df_ss = trans_ss.fit_transform(x)
pd.DataFrame(df_ss)

,0,1,2,3,4,5,6,7
0,-0.530377,-0.502445,-1.231645,-0.510152,0.902587,-0.307562,0.619306,0.737695
1,0.571831,0.786845,-1.231645,-0.510152,-1.107926,-0.307562,-1.614710,-1.355574
2,-0.254825,-0.488854,0.811922,-0.510152,0.902587,-0.307562,0.619306,-1.355574
3,0.365167,0.420730,-1.231645,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
4,0.365167,-0.486337,0.811922,-0.510152,0.902587,-0.307562,0.619306,0.737695
...,...,...,...,...,...,...,...,...
886,-0.185937,-0.386671,0.811922,1.960202,-1.107926,-0.307562,0.619306,0.737695
887,-0.737041,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
888,NaN,-0.176263,-1.231645,-0.510152,0.902587,-0.307562,0.619306,-1.355574
889,-0.254825,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,-1.614710,0.737695
890,0.158503,-0.492378,0.811922,-0.510152,0.902587,3.251373,-1.614710,0.737695