In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df['Travelalone'] = np.where((df['SibSp'] + df['Parch']) > 0, 0, 1).astype('uint8')

In [8]:
df1 = df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin'], axis= 1)

In [10]:
df1.isna().sum()

Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
Embarked         2
Travelalone      0
dtype: int64

In [14]:
df['Age'].fillna(df1['Age'].median(skipna=True), inplace=True)

/tmp/ipykernel_91744/2169829194.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df1['Age'].median(skipna=True), inplace=True)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [15]:
df1.head()

   Survived  Pclass     Sex   Age     Fare Embarked  Travelalone
0         0       3    male  22.0   7.2500        S            0
1         1       1  female  38.0  71.2833        C            0
2         1       3  female  26.0   7.9250        S            1
3         1       1  female  35.0  53.1000        S            0
4         0       3    male  35.0   8.0500        S            1

In [16]:
df_titanic = pd.get_dummies(df1, columns=['Pclass', 'Embarked', 'Sex'], drop_first=True)

In [17]:
df_titanic.head()

,Survived,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,0,22.0,7.2500,0,False,True,False,True,True
1,1,38.0,71.2833,0,False,False,False,False,False
2,1,26.0,7.9250,1,False,True,False,True,False
3,1,35.0,53.1000,0,False,False,False,True,False
4,0,35.0,8.0500,1,False,True,False,True,True

In [20]:
x = df_titanic.drop(['Survived'], axis = 1)
y = df_titanic['Survived']

In [21]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [22]:
trans_mm = MinMaxScaler()
trans_ss = StandardScaler()

In [23]:
df_mm = trans_mm.fit_transform(x)
pd.DataFrame(df_mm)

            0         1    2    3    4    5    6    7
0    0.271174  0.014151  0.0  0.0  1.0  0.0  1.0  1.0
1    0.472229  0.139136  0.0  0.0  0.0  0.0  0.0  0.0
2    0.321438  0.015469  1.0  0.0  1.0  0.0  1.0  0.0
3    0.434531  0.103644  0.0  0.0  0.0  0.0  1.0  0.0
4    0.434531  0.015713  1.0  0.0  1.0  0.0  1.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...
886  0.334004  0.025374  1.0  1.0  0.0  0.0  1.0  1.0
887  0.233476  0.058556  1.0  0.0  0.0  0.0  1.0  0.0
888       NaN  0.045771  0.0  0.0  1.0  0.0  1.0  0.0
889  0.321438  0.058556  1.0  0.0  0.0  0.0  0.0  1.0
890  0.396833  0.015127  1.0  0.0  1.0  1.0  0.0  1.0

[891 rows x 8 columns]

In [24]:
df_ss = trans_ss.fit_transform(x)
pd.DataFrame(df_ss)

,0,1,2,3,4,5,6,7
0,-0.530377,-0.502445,-1.231645,-0.510152,0.902587,-0.307562,0.619306,0.737695
1,0.571831,0.786845,-1.231645,-0.510152,-1.107926,-0.307562,-1.614710,-1.355574
2,-0.254825,-0.488854,0.811922,-0.510152,0.902587,-0.307562,0.619306,-1.355574
3,0.365167,0.420730,-1.231645,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
4,0.365167,-0.486337,0.811922,-0.510152,0.902587,-0.307562,0.619306,0.737695
...,...,...,...,...,...,...,...,...
886,-0.185937,-0.386671,0.811922,1.960202,-1.107926,-0.307562,0.619306,0.737695
887,-0.737041,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
888,NaN,-0.176263,-1.231645,-0.510152,0.902587,-0.307562,0.619306,-1.355574
889,-0.254825,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,-1.614710,0.737695
890,0.158503,-0.492378,0.811922,-0.510152,0.902587,3.251373,-1.614710,0.737695